### YamlMime:Landing
title: Documentation relative à Ansible sur Azure
summary: Découvrez comment automatiser l’approvisionnement du cloud, la gestion de la configuration et le déploiement des applications avec Ansible.
metadata:
  title: Documentation relative à Ansible sur Azure
  description: Découvrez comment automatiser l’approvisionnement du cloud, la gestion de la configuration et le déploiement des applications avec Ansible.
  services: azure
  ms.service: ansible
  ms.topic: landing-page
  author: TomArcherMsft
  ms.author: tarcher
  ms.date: 09/11/2019
  ms.openlocfilehash: ccdf9055fbdb72f0f0059d9bfe27bee41952446e
  ms.sourcegitcommit: 0947111b263015136bca0e6ec5a8c570b3f700ff
  ms.translationtype: HT
  ms.contentlocale: fr-FR
  ms.lasthandoff: 03/24/2020
  ms.locfileid: "72389004"
landingContent:
- title: À propos d’Ansible sur Azure
  linkLists:
  - linkListType: overview
    links:
    - text: À propos d’Ansible sur Azure
      url: ansible-overview.md
  - linkListType: reference
    links:
    - text: Composants et fonctionnalités
      url: ./ansible-matrix.md
    - text: Tous les modules pour Azure
      url: https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules#azure
- title: Installer et configurer Ansible
  linkLists:
  - linkListType: quickstart
    links:
    - text: Déployer un modèle de solution Ansible sur CentOS
      url: ansible-deploy-solution-template.md
    - text: Installer Ansible sur des machines virtuelles Linux
      url: /azure/virtual-machines/linux/ansible-install-configure
    - text: Exécuter des playbooks dans Cloud Shell
      url: ansible-run-playbook-in-cloudshell.md
  - linkListType: tutorial
    links:
    - text: Configurer un inventaire dynamique
      url: ansible-manage-azure-dynamic-inventories.md
  - linkListType: download
    links:
    - text: Extension de Visual Studio Code pour Ansible
      url: https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible
- title: Gérer les machines virtuelles
  linkLists:
  - linkListType: quickstart
    links:
    - text: Configurer des machines virtuelles Linux
      url: /azure/virtual-machines/linux/ansible-create-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - text: Gérer des machines virtuelles Linux
      url: /azure/virtual-machines/linux/ansible-manage-linux-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - text: Créer depuis Shared Image Gallery
      url: ansible-vm-create-from-shared-generalized-image.md
- title: Gérer des groupes de machines virtuelles identiques
  linkLists:
  - linkListType: tutorial
    links:
    - text: Configurer des groupes de machines virtuelles identiques
      url: ansible-create-configure-vmss.md
    - text: Déployer des applications dans des groupes de machines virtuelles identiques
      url: ansible-deploy-app-vmss.md
    - text: Mettre automatiquement à l’échelle des groupes de machines virtuelles identiques
      url: ansible-auto-scale-vmss.md
    - text: Mettre à jour une image personnalisée
      url: ansible-vmss-update-image.md
    - text: Créer depuis Shared Image Gallery
      url: ansible-vm-create-from-shared-generalized-image.md
- title: Gérer des réseaux virtuels
  linkLists:
  - linkListType: tutorial
    links:
    - text: Configurer le peering
      url: ansible-vnet-peering-configure.md
    - text: Configurer des tables de routage
      url: ansible-create-configure-route-table.md
- title: Gérer AKS
  linkLists:
  - linkListType: tutorial
    links:
    - text: Configurer des clusters AKS
      url: ansible-create-configure-aks.md
    - text: Configurer le réseau Azure CNI
      url: ansible-aks-configure-cni-networking.md
    - text: Configurer le réseau kubenet
      url: ansible-aks-configure-kubenet-networking.md
    - text: Configurer des rôles RBAC dans un cluster AKS
      url: ansible-aks-configure-rbac.md
